/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedAiLearningRouteImport } from './routes/_authenticated/ai-learning'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase-orders.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedYarnSuppliersRouteImport } from './routes/_authenticated/yarn.suppliers'
import { Route as AuthenticatedYarnShadesRouteImport } from './routes/_authenticated/yarn.shades'
import { Route as AuthenticatedReportsPendencyPoRouteImport } from './routes/_authenticated/reports.pendency-po'
import { Route as AuthenticatedReportsPendencyItemRouteImport } from './routes/_authenticated/reports.pendency-item'
import { Route as AuthenticatedPurchaseOrdersPdfImportHistoryRouteImport } from './routes/_authenticated/purchase-orders.pdf-import-history'
import { Route as AuthenticatedPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchase-orders.new'
import { Route as AuthenticatedPurchaseOrdersImportPdfRouteImport } from './routes/_authenticated/purchase-orders.import-pdf'
import { Route as AuthenticatedPurchaseOrdersImportHistoryRouteImport } from './routes/_authenticated/purchase-orders.import-history'
import { Route as AuthenticatedPurchaseOrdersImportRouteImport } from './routes/_authenticated/purchase-orders.import'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesImportRouteImport } from './routes/_authenticated/invoices.import'
import { Route as AuthenticatedAdminUserActivityRouteImport } from './routes/_authenticated/admin.user-activity'
import { Route as AuthenticatedAdminDailyReportRouteImport } from './routes/_authenticated/admin.daily-report'
import { Route as AuthenticatedAdminAuditLogsRouteImport } from './routes/_authenticated/admin.audit-logs'
import { Route as AuthenticatedYarnSampleOrdersIndexRouteImport } from './routes/_authenticated/yarn.sample-orders.index'
import { Route as AuthenticatedYarnProductionOrdersIndexRouteImport } from './routes/_authenticated/yarn.production-orders.index'
import { Route as AuthenticatedYarnInwardsIndexRouteImport } from './routes/_authenticated/yarn.inwards.index'
import { Route as AuthenticatedYarnSampleOrdersNewRouteImport } from './routes/_authenticated/yarn.sample-orders.new'
import { Route as AuthenticatedYarnSampleOrdersIdRouteImport } from './routes/_authenticated/yarn.sample-orders.$id'
import { Route as AuthenticatedYarnProductionOrdersNewRouteImport } from './routes/_authenticated/yarn.production-orders.new'
import { Route as AuthenticatedYarnProductionOrdersIdRouteImport } from './routes/_authenticated/yarn.production-orders.$id'
import { Route as AuthenticatedYarnInwardsNewRouteImport } from './routes/_authenticated/yarn.inwards.new'
import { Route as AuthenticatedYarnInwardsIdRouteImport } from './routes/_authenticated/yarn.inwards.$id'
import { Route as AuthenticatedPurchaseOrdersIdEditRouteImport } from './routes/_authenticated/purchase-orders.$id.edit'
import { Route as AuthenticatedInvoicesIdEditRouteImport } from './routes/_authenticated/invoices.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiLearningRoute = AuthenticatedAiLearningRouteImport.update({
  id: '/ai-learning',
  path: '/ai-learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnSuppliersRoute =
  AuthenticatedYarnSuppliersRouteImport.update({
    id: '/yarn/suppliers',
    path: '/yarn/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnShadesRoute = AuthenticatedYarnShadesRouteImport.update({
  id: '/yarn/shades',
  path: '/yarn/shades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsPendencyPoRoute =
  AuthenticatedReportsPendencyPoRouteImport.update({
    id: '/reports/pendency-po',
    path: '/reports/pendency-po',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsPendencyItemRoute =
  AuthenticatedReportsPendencyItemRouteImport.update({
    id: '/reports/pendency-item',
    path: '/reports/pendency-item',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersPdfImportHistoryRoute =
  AuthenticatedPurchaseOrdersPdfImportHistoryRouteImport.update({
    id: '/purchase-orders/pdf-import-history',
    path: '/purchase-orders/pdf-import-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersNewRoute =
  AuthenticatedPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders/new',
    path: '/purchase-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersImportPdfRoute =
  AuthenticatedPurchaseOrdersImportPdfRouteImport.update({
    id: '/purchase-orders/import-pdf',
    path: '/purchase-orders/import-pdf',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersImportHistoryRoute =
  AuthenticatedPurchaseOrdersImportHistoryRouteImport.update({
    id: '/purchase-orders/import-history',
    path: '/purchase-orders/import-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersImportRoute =
  AuthenticatedPurchaseOrdersImportRouteImport.update({
    id: '/purchase-orders/import',
    path: '/purchase-orders/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesImportRoute =
  AuthenticatedInvoicesImportRouteImport.update({
    id: '/invoices/import',
    path: '/invoices/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUserActivityRoute =
  AuthenticatedAdminUserActivityRouteImport.update({
    id: '/admin/user-activity',
    path: '/admin/user-activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminDailyReportRoute =
  AuthenticatedAdminDailyReportRouteImport.update({
    id: '/admin/daily-report',
    path: '/admin/daily-report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAuditLogsRoute =
  AuthenticatedAdminAuditLogsRouteImport.update({
    id: '/admin/audit-logs',
    path: '/admin/audit-logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnSampleOrdersIndexRoute =
  AuthenticatedYarnSampleOrdersIndexRouteImport.update({
    id: '/yarn/sample-orders/',
    path: '/yarn/sample-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnProductionOrdersIndexRoute =
  AuthenticatedYarnProductionOrdersIndexRouteImport.update({
    id: '/yarn/production-orders/',
    path: '/yarn/production-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnInwardsIndexRoute =
  AuthenticatedYarnInwardsIndexRouteImport.update({
    id: '/yarn/inwards/',
    path: '/yarn/inwards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnSampleOrdersNewRoute =
  AuthenticatedYarnSampleOrdersNewRouteImport.update({
    id: '/yarn/sample-orders/new',
    path: '/yarn/sample-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnSampleOrdersIdRoute =
  AuthenticatedYarnSampleOrdersIdRouteImport.update({
    id: '/yarn/sample-orders/$id',
    path: '/yarn/sample-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnProductionOrdersNewRoute =
  AuthenticatedYarnProductionOrdersNewRouteImport.update({
    id: '/yarn/production-orders/new',
    path: '/yarn/production-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnProductionOrdersIdRoute =
  AuthenticatedYarnProductionOrdersIdRouteImport.update({
    id: '/yarn/production-orders/$id',
    path: '/yarn/production-orders/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnInwardsNewRoute =
  AuthenticatedYarnInwardsNewRouteImport.update({
    id: '/yarn/inwards/new',
    path: '/yarn/inwards/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedYarnInwardsIdRoute =
  AuthenticatedYarnInwardsIdRouteImport.update({
    id: '/yarn/inwards/$id',
    path: '/yarn/inwards/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdEditRoute =
  AuthenticatedPurchaseOrdersIdEditRouteImport.update({
    id: '/purchase-orders/$id/edit',
    path: '/purchase-orders/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdEditRoute =
  AuthenticatedInvoicesIdEditRouteImport.update({
    id: '/invoices/$id/edit',
    path: '/invoices/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-learning': typeof AuthenticatedAiLearningRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/daily-report': typeof AuthenticatedAdminDailyReportRoute
  '/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/purchase-orders/import': typeof AuthenticatedPurchaseOrdersImportRoute
  '/purchase-orders/import-history': typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  '/purchase-orders/import-pdf': typeof AuthenticatedPurchaseOrdersImportPdfRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/purchase-orders/pdf-import-history': typeof AuthenticatedPurchaseOrdersPdfImportHistoryRoute
  '/reports/pendency-item': typeof AuthenticatedReportsPendencyItemRoute
  '/reports/pendency-po': typeof AuthenticatedReportsPendencyPoRoute
  '/yarn/shades': typeof AuthenticatedYarnShadesRoute
  '/yarn/suppliers': typeof AuthenticatedYarnSuppliersRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
  '/yarn/inwards/$id': typeof AuthenticatedYarnInwardsIdRoute
  '/yarn/inwards/new': typeof AuthenticatedYarnInwardsNewRoute
  '/yarn/production-orders/$id': typeof AuthenticatedYarnProductionOrdersIdRoute
  '/yarn/production-orders/new': typeof AuthenticatedYarnProductionOrdersNewRoute
  '/yarn/sample-orders/$id': typeof AuthenticatedYarnSampleOrdersIdRoute
  '/yarn/sample-orders/new': typeof AuthenticatedYarnSampleOrdersNewRoute
  '/yarn/inwards/': typeof AuthenticatedYarnInwardsIndexRoute
  '/yarn/production-orders/': typeof AuthenticatedYarnProductionOrdersIndexRoute
  '/yarn/sample-orders/': typeof AuthenticatedYarnSampleOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-learning': typeof AuthenticatedAiLearningRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/admin/daily-report': typeof AuthenticatedAdminDailyReportRoute
  '/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/purchase-orders/import': typeof AuthenticatedPurchaseOrdersImportRoute
  '/purchase-orders/import-history': typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  '/purchase-orders/import-pdf': typeof AuthenticatedPurchaseOrdersImportPdfRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/purchase-orders/pdf-import-history': typeof AuthenticatedPurchaseOrdersPdfImportHistoryRoute
  '/reports/pendency-item': typeof AuthenticatedReportsPendencyItemRoute
  '/reports/pendency-po': typeof AuthenticatedReportsPendencyPoRoute
  '/yarn/shades': typeof AuthenticatedYarnShadesRoute
  '/yarn/suppliers': typeof AuthenticatedYarnSuppliersRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
  '/yarn/inwards/$id': typeof AuthenticatedYarnInwardsIdRoute
  '/yarn/inwards/new': typeof AuthenticatedYarnInwardsNewRoute
  '/yarn/production-orders/$id': typeof AuthenticatedYarnProductionOrdersIdRoute
  '/yarn/production-orders/new': typeof AuthenticatedYarnProductionOrdersNewRoute
  '/yarn/sample-orders/$id': typeof AuthenticatedYarnSampleOrdersIdRoute
  '/yarn/sample-orders/new': typeof AuthenticatedYarnSampleOrdersNewRoute
  '/yarn/inwards': typeof AuthenticatedYarnInwardsIndexRoute
  '/yarn/production-orders': typeof AuthenticatedYarnProductionOrdersIndexRoute
  '/yarn/sample-orders': typeof AuthenticatedYarnSampleOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/ai-learning': typeof AuthenticatedAiLearningRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/audit-logs': typeof AuthenticatedAdminAuditLogsRoute
  '/_authenticated/admin/daily-report': typeof AuthenticatedAdminDailyReportRoute
  '/_authenticated/admin/user-activity': typeof AuthenticatedAdminUserActivityRoute
  '/_authenticated/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/purchase-orders/import': typeof AuthenticatedPurchaseOrdersImportRoute
  '/_authenticated/purchase-orders/import-history': typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  '/_authenticated/purchase-orders/import-pdf': typeof AuthenticatedPurchaseOrdersImportPdfRoute
  '/_authenticated/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/_authenticated/purchase-orders/pdf-import-history': typeof AuthenticatedPurchaseOrdersPdfImportHistoryRoute
  '/_authenticated/reports/pendency-item': typeof AuthenticatedReportsPendencyItemRoute
  '/_authenticated/reports/pendency-po': typeof AuthenticatedReportsPendencyPoRoute
  '/_authenticated/yarn/shades': typeof AuthenticatedYarnShadesRoute
  '/_authenticated/yarn/suppliers': typeof AuthenticatedYarnSuppliersRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/_authenticated/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
  '/_authenticated/yarn/inwards/$id': typeof AuthenticatedYarnInwardsIdRoute
  '/_authenticated/yarn/inwards/new': typeof AuthenticatedYarnInwardsNewRoute
  '/_authenticated/yarn/production-orders/$id': typeof AuthenticatedYarnProductionOrdersIdRoute
  '/_authenticated/yarn/production-orders/new': typeof AuthenticatedYarnProductionOrdersNewRoute
  '/_authenticated/yarn/sample-orders/$id': typeof AuthenticatedYarnSampleOrdersIdRoute
  '/_authenticated/yarn/sample-orders/new': typeof AuthenticatedYarnSampleOrdersNewRoute
  '/_authenticated/yarn/inwards/': typeof AuthenticatedYarnInwardsIndexRoute
  '/_authenticated/yarn/production-orders/': typeof AuthenticatedYarnProductionOrdersIndexRoute
  '/_authenticated/yarn/sample-orders/': typeof AuthenticatedYarnSampleOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-learning'
    | '/brands'
    | '/clients'
    | '/dashboard'
    | '/admin/audit-logs'
    | '/admin/daily-report'
    | '/admin/user-activity'
    | '/invoices/import'
    | '/invoices/new'
    | '/purchase-orders/import'
    | '/purchase-orders/import-history'
    | '/purchase-orders/import-pdf'
    | '/purchase-orders/new'
    | '/purchase-orders/pdf-import-history'
    | '/reports/pendency-item'
    | '/reports/pendency-po'
    | '/yarn/shades'
    | '/yarn/suppliers'
    | '/invoices/'
    | '/purchase-orders/'
    | '/invoices/$id/edit'
    | '/purchase-orders/$id/edit'
    | '/yarn/inwards/$id'
    | '/yarn/inwards/new'
    | '/yarn/production-orders/$id'
    | '/yarn/production-orders/new'
    | '/yarn/sample-orders/$id'
    | '/yarn/sample-orders/new'
    | '/yarn/inwards/'
    | '/yarn/production-orders/'
    | '/yarn/sample-orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-learning'
    | '/brands'
    | '/clients'
    | '/dashboard'
    | '/admin/audit-logs'
    | '/admin/daily-report'
    | '/admin/user-activity'
    | '/invoices/import'
    | '/invoices/new'
    | '/purchase-orders/import'
    | '/purchase-orders/import-history'
    | '/purchase-orders/import-pdf'
    | '/purchase-orders/new'
    | '/purchase-orders/pdf-import-history'
    | '/reports/pendency-item'
    | '/reports/pendency-po'
    | '/yarn/shades'
    | '/yarn/suppliers'
    | '/invoices'
    | '/purchase-orders'
    | '/invoices/$id/edit'
    | '/purchase-orders/$id/edit'
    | '/yarn/inwards/$id'
    | '/yarn/inwards/new'
    | '/yarn/production-orders/$id'
    | '/yarn/production-orders/new'
    | '/yarn/sample-orders/$id'
    | '/yarn/sample-orders/new'
    | '/yarn/inwards'
    | '/yarn/production-orders'
    | '/yarn/sample-orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/ai-learning'
    | '/_authenticated/brands'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/audit-logs'
    | '/_authenticated/admin/daily-report'
    | '/_authenticated/admin/user-activity'
    | '/_authenticated/invoices/import'
    | '/_authenticated/invoices/new'
    | '/_authenticated/purchase-orders/import'
    | '/_authenticated/purchase-orders/import-history'
    | '/_authenticated/purchase-orders/import-pdf'
    | '/_authenticated/purchase-orders/new'
    | '/_authenticated/purchase-orders/pdf-import-history'
    | '/_authenticated/reports/pendency-item'
    | '/_authenticated/reports/pendency-po'
    | '/_authenticated/yarn/shades'
    | '/_authenticated/yarn/suppliers'
    | '/_authenticated/invoices/'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/invoices/$id/edit'
    | '/_authenticated/purchase-orders/$id/edit'
    | '/_authenticated/yarn/inwards/$id'
    | '/_authenticated/yarn/inwards/new'
    | '/_authenticated/yarn/production-orders/$id'
    | '/_authenticated/yarn/production-orders/new'
    | '/_authenticated/yarn/sample-orders/$id'
    | '/_authenticated/yarn/sample-orders/new'
    | '/_authenticated/yarn/inwards/'
    | '/_authenticated/yarn/production-orders/'
    | '/_authenticated/yarn/sample-orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-learning': {
      id: '/_authenticated/ai-learning'
      path: '/ai-learning'
      fullPath: '/ai-learning'
      preLoaderRoute: typeof AuthenticatedAiLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/suppliers': {
      id: '/_authenticated/yarn/suppliers'
      path: '/yarn/suppliers'
      fullPath: '/yarn/suppliers'
      preLoaderRoute: typeof AuthenticatedYarnSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/shades': {
      id: '/_authenticated/yarn/shades'
      path: '/yarn/shades'
      fullPath: '/yarn/shades'
      preLoaderRoute: typeof AuthenticatedYarnShadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/pendency-po': {
      id: '/_authenticated/reports/pendency-po'
      path: '/reports/pendency-po'
      fullPath: '/reports/pendency-po'
      preLoaderRoute: typeof AuthenticatedReportsPendencyPoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/pendency-item': {
      id: '/_authenticated/reports/pendency-item'
      path: '/reports/pendency-item'
      fullPath: '/reports/pendency-item'
      preLoaderRoute: typeof AuthenticatedReportsPendencyItemRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/pdf-import-history': {
      id: '/_authenticated/purchase-orders/pdf-import-history'
      path: '/purchase-orders/pdf-import-history'
      fullPath: '/purchase-orders/pdf-import-history'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersPdfImportHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/new': {
      id: '/_authenticated/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/import-pdf': {
      id: '/_authenticated/purchase-orders/import-pdf'
      path: '/purchase-orders/import-pdf'
      fullPath: '/purchase-orders/import-pdf'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersImportPdfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/import-history': {
      id: '/_authenticated/purchase-orders/import-history'
      path: '/purchase-orders/import-history'
      fullPath: '/purchase-orders/import-history'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersImportHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/import': {
      id: '/_authenticated/purchase-orders/import'
      path: '/purchase-orders/import'
      fullPath: '/purchase-orders/import'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/import': {
      id: '/_authenticated/invoices/import'
      path: '/invoices/import'
      fullPath: '/invoices/import'
      preLoaderRoute: typeof AuthenticatedInvoicesImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/user-activity': {
      id: '/_authenticated/admin/user-activity'
      path: '/admin/user-activity'
      fullPath: '/admin/user-activity'
      preLoaderRoute: typeof AuthenticatedAdminUserActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/daily-report': {
      id: '/_authenticated/admin/daily-report'
      path: '/admin/daily-report'
      fullPath: '/admin/daily-report'
      preLoaderRoute: typeof AuthenticatedAdminDailyReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit-logs': {
      id: '/_authenticated/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AuthenticatedAdminAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/sample-orders/': {
      id: '/_authenticated/yarn/sample-orders/'
      path: '/yarn/sample-orders'
      fullPath: '/yarn/sample-orders/'
      preLoaderRoute: typeof AuthenticatedYarnSampleOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/production-orders/': {
      id: '/_authenticated/yarn/production-orders/'
      path: '/yarn/production-orders'
      fullPath: '/yarn/production-orders/'
      preLoaderRoute: typeof AuthenticatedYarnProductionOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/inwards/': {
      id: '/_authenticated/yarn/inwards/'
      path: '/yarn/inwards'
      fullPath: '/yarn/inwards/'
      preLoaderRoute: typeof AuthenticatedYarnInwardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/sample-orders/new': {
      id: '/_authenticated/yarn/sample-orders/new'
      path: '/yarn/sample-orders/new'
      fullPath: '/yarn/sample-orders/new'
      preLoaderRoute: typeof AuthenticatedYarnSampleOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/sample-orders/$id': {
      id: '/_authenticated/yarn/sample-orders/$id'
      path: '/yarn/sample-orders/$id'
      fullPath: '/yarn/sample-orders/$id'
      preLoaderRoute: typeof AuthenticatedYarnSampleOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/production-orders/new': {
      id: '/_authenticated/yarn/production-orders/new'
      path: '/yarn/production-orders/new'
      fullPath: '/yarn/production-orders/new'
      preLoaderRoute: typeof AuthenticatedYarnProductionOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/production-orders/$id': {
      id: '/_authenticated/yarn/production-orders/$id'
      path: '/yarn/production-orders/$id'
      fullPath: '/yarn/production-orders/$id'
      preLoaderRoute: typeof AuthenticatedYarnProductionOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/inwards/new': {
      id: '/_authenticated/yarn/inwards/new'
      path: '/yarn/inwards/new'
      fullPath: '/yarn/inwards/new'
      preLoaderRoute: typeof AuthenticatedYarnInwardsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yarn/inwards/$id': {
      id: '/_authenticated/yarn/inwards/$id'
      path: '/yarn/inwards/$id'
      fullPath: '/yarn/inwards/$id'
      preLoaderRoute: typeof AuthenticatedYarnInwardsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/$id/edit': {
      id: '/_authenticated/purchase-orders/$id/edit'
      path: '/purchase-orders/$id/edit'
      fullPath: '/purchase-orders/$id/edit'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id/edit': {
      id: '/_authenticated/invoices/$id/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiLearningRoute: typeof AuthenticatedAiLearningRoute
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminAuditLogsRoute: typeof AuthenticatedAdminAuditLogsRoute
  AuthenticatedAdminDailyReportRoute: typeof AuthenticatedAdminDailyReportRoute
  AuthenticatedAdminUserActivityRoute: typeof AuthenticatedAdminUserActivityRoute
  AuthenticatedInvoicesImportRoute: typeof AuthenticatedInvoicesImportRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedPurchaseOrdersImportRoute: typeof AuthenticatedPurchaseOrdersImportRoute
  AuthenticatedPurchaseOrdersImportHistoryRoute: typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  AuthenticatedPurchaseOrdersImportPdfRoute: typeof AuthenticatedPurchaseOrdersImportPdfRoute
  AuthenticatedPurchaseOrdersNewRoute: typeof AuthenticatedPurchaseOrdersNewRoute
  AuthenticatedPurchaseOrdersPdfImportHistoryRoute: typeof AuthenticatedPurchaseOrdersPdfImportHistoryRoute
  AuthenticatedReportsPendencyItemRoute: typeof AuthenticatedReportsPendencyItemRoute
  AuthenticatedReportsPendencyPoRoute: typeof AuthenticatedReportsPendencyPoRoute
  AuthenticatedYarnShadesRoute: typeof AuthenticatedYarnShadesRoute
  AuthenticatedYarnSuppliersRoute: typeof AuthenticatedYarnSuppliersRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedInvoicesIdEditRoute: typeof AuthenticatedInvoicesIdEditRoute
  AuthenticatedPurchaseOrdersIdEditRoute: typeof AuthenticatedPurchaseOrdersIdEditRoute
  AuthenticatedYarnInwardsIdRoute: typeof AuthenticatedYarnInwardsIdRoute
  AuthenticatedYarnInwardsNewRoute: typeof AuthenticatedYarnInwardsNewRoute
  AuthenticatedYarnProductionOrdersIdRoute: typeof AuthenticatedYarnProductionOrdersIdRoute
  AuthenticatedYarnProductionOrdersNewRoute: typeof AuthenticatedYarnProductionOrdersNewRoute
  AuthenticatedYarnSampleOrdersIdRoute: typeof AuthenticatedYarnSampleOrdersIdRoute
  AuthenticatedYarnSampleOrdersNewRoute: typeof AuthenticatedYarnSampleOrdersNewRoute
  AuthenticatedYarnInwardsIndexRoute: typeof AuthenticatedYarnInwardsIndexRoute
  AuthenticatedYarnProductionOrdersIndexRoute: typeof AuthenticatedYarnProductionOrdersIndexRoute
  AuthenticatedYarnSampleOrdersIndexRoute: typeof AuthenticatedYarnSampleOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiLearningRoute: AuthenticatedAiLearningRoute,
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminAuditLogsRoute: AuthenticatedAdminAuditLogsRoute,
  AuthenticatedAdminDailyReportRoute: AuthenticatedAdminDailyReportRoute,
  AuthenticatedAdminUserActivityRoute: AuthenticatedAdminUserActivityRoute,
  AuthenticatedInvoicesImportRoute: AuthenticatedInvoicesImportRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedPurchaseOrdersImportRoute:
    AuthenticatedPurchaseOrdersImportRoute,
  AuthenticatedPurchaseOrdersImportHistoryRoute:
    AuthenticatedPurchaseOrdersImportHistoryRoute,
  AuthenticatedPurchaseOrdersImportPdfRoute:
    AuthenticatedPurchaseOrdersImportPdfRoute,
  AuthenticatedPurchaseOrdersNewRoute: AuthenticatedPurchaseOrdersNewRoute,
  AuthenticatedPurchaseOrdersPdfImportHistoryRoute:
    AuthenticatedPurchaseOrdersPdfImportHistoryRoute,
  AuthenticatedReportsPendencyItemRoute: AuthenticatedReportsPendencyItemRoute,
  AuthenticatedReportsPendencyPoRoute: AuthenticatedReportsPendencyPoRoute,
  AuthenticatedYarnShadesRoute: AuthenticatedYarnShadesRoute,
  AuthenticatedYarnSuppliersRoute: AuthenticatedYarnSuppliersRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedInvoicesIdEditRoute: AuthenticatedInvoicesIdEditRoute,
  AuthenticatedPurchaseOrdersIdEditRoute:
    AuthenticatedPurchaseOrdersIdEditRoute,
  AuthenticatedYarnInwardsIdRoute: AuthenticatedYarnInwardsIdRoute,
  AuthenticatedYarnInwardsNewRoute: AuthenticatedYarnInwardsNewRoute,
  AuthenticatedYarnProductionOrdersIdRoute:
    AuthenticatedYarnProductionOrdersIdRoute,
  AuthenticatedYarnProductionOrdersNewRoute:
    AuthenticatedYarnProductionOrdersNewRoute,
  AuthenticatedYarnSampleOrdersIdRoute: AuthenticatedYarnSampleOrdersIdRoute,
  AuthenticatedYarnSampleOrdersNewRoute: AuthenticatedYarnSampleOrdersNewRoute,
  AuthenticatedYarnInwardsIndexRoute: AuthenticatedYarnInwardsIndexRoute,
  AuthenticatedYarnProductionOrdersIndexRoute:
    AuthenticatedYarnProductionOrdersIndexRoute,
  AuthenticatedYarnSampleOrdersIndexRoute:
    AuthenticatedYarnSampleOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
