/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiExtractPoPdfRouteImport } from './routes/api/extract-po-pdf'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedPurchaseOrdersIndexRouteImport } from './routes/_authenticated/purchase-orders.index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedPurchaseOrdersNewRouteImport } from './routes/_authenticated/purchase-orders.new'
import { Route as AuthenticatedPurchaseOrdersImportHistoryRouteImport } from './routes/_authenticated/purchase-orders.import-history'
import { Route as AuthenticatedPurchaseOrdersImportRouteImport } from './routes/_authenticated/purchase-orders.import'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesImportRouteImport } from './routes/_authenticated/invoices.import'
import { Route as AuthenticatedPurchaseOrdersIdEditRouteImport } from './routes/_authenticated/purchase-orders.$id.edit'
import { Route as AuthenticatedInvoicesIdEditRouteImport } from './routes/_authenticated/invoices.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractPoPdfRoute = ApiExtractPoPdfRouteImport.update({
  id: '/api/extract-po-pdf',
  path: '/api/extract-po-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrdersIndexRoute =
  AuthenticatedPurchaseOrdersIndexRouteImport.update({
    id: '/purchase-orders/',
    path: '/purchase-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersNewRoute =
  AuthenticatedPurchaseOrdersNewRouteImport.update({
    id: '/purchase-orders/new',
    path: '/purchase-orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersImportHistoryRoute =
  AuthenticatedPurchaseOrdersImportHistoryRouteImport.update({
    id: '/purchase-orders/import-history',
    path: '/purchase-orders/import-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersImportRoute =
  AuthenticatedPurchaseOrdersImportRouteImport.update({
    id: '/purchase-orders/import',
    path: '/purchase-orders/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesImportRoute =
  AuthenticatedInvoicesImportRouteImport.update({
    id: '/invoices/import',
    path: '/invoices/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPurchaseOrdersIdEditRoute =
  AuthenticatedPurchaseOrdersIdEditRouteImport.update({
    id: '/purchase-orders/$id/edit',
    path: '/purchase-orders/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdEditRoute =
  AuthenticatedInvoicesIdEditRouteImport.update({
    id: '/invoices/$id/edit',
    path: '/invoices/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/extract-po-pdf': typeof ApiExtractPoPdfRoute
  '/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/purchase-orders/import': typeof AuthenticatedPurchaseOrdersImportRoute
  '/purchase-orders/import-history': typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/extract-po-pdf': typeof ApiExtractPoPdfRoute
  '/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/purchase-orders/import': typeof AuthenticatedPurchaseOrdersImportRoute
  '/purchase-orders/import-history': typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  '/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/extract-po-pdf': typeof ApiExtractPoPdfRoute
  '/_authenticated/invoices/import': typeof AuthenticatedInvoicesImportRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/purchase-orders/import': typeof AuthenticatedPurchaseOrdersImportRoute
  '/_authenticated/purchase-orders/import-history': typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  '/_authenticated/purchase-orders/new': typeof AuthenticatedPurchaseOrdersNewRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/purchase-orders/': typeof AuthenticatedPurchaseOrdersIndexRoute
  '/_authenticated/invoices/$id/edit': typeof AuthenticatedInvoicesIdEditRoute
  '/_authenticated/purchase-orders/$id/edit': typeof AuthenticatedPurchaseOrdersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/brands'
    | '/clients'
    | '/dashboard'
    | '/api/extract-po-pdf'
    | '/invoices/import'
    | '/invoices/new'
    | '/purchase-orders/import'
    | '/purchase-orders/import-history'
    | '/purchase-orders/new'
    | '/invoices/'
    | '/purchase-orders/'
    | '/invoices/$id/edit'
    | '/purchase-orders/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/brands'
    | '/clients'
    | '/dashboard'
    | '/api/extract-po-pdf'
    | '/invoices/import'
    | '/invoices/new'
    | '/purchase-orders/import'
    | '/purchase-orders/import-history'
    | '/purchase-orders/new'
    | '/invoices'
    | '/purchase-orders'
    | '/invoices/$id/edit'
    | '/purchase-orders/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/brands'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/api/extract-po-pdf'
    | '/_authenticated/invoices/import'
    | '/_authenticated/invoices/new'
    | '/_authenticated/purchase-orders/import'
    | '/_authenticated/purchase-orders/import-history'
    | '/_authenticated/purchase-orders/new'
    | '/_authenticated/invoices/'
    | '/_authenticated/purchase-orders/'
    | '/_authenticated/invoices/$id/edit'
    | '/_authenticated/purchase-orders/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiExtractPoPdfRoute: typeof ApiExtractPoPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-po-pdf': {
      id: '/api/extract-po-pdf'
      path: '/api/extract-po-pdf'
      fullPath: '/api/extract-po-pdf'
      preLoaderRoute: typeof ApiExtractPoPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/': {
      id: '/_authenticated/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/new': {
      id: '/_authenticated/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/import-history': {
      id: '/_authenticated/purchase-orders/import-history'
      path: '/purchase-orders/import-history'
      fullPath: '/purchase-orders/import-history'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersImportHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/import': {
      id: '/_authenticated/purchase-orders/import'
      path: '/purchase-orders/import'
      fullPath: '/purchase-orders/import'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/import': {
      id: '/_authenticated/invoices/import'
      path: '/invoices/import'
      fullPath: '/invoices/import'
      preLoaderRoute: typeof AuthenticatedInvoicesImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders/$id/edit': {
      id: '/_authenticated/purchase-orders/$id/edit'
      path: '/purchase-orders/$id/edit'
      fullPath: '/purchase-orders/$id/edit'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id/edit': {
      id: '/_authenticated/invoices/$id/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvoicesImportRoute: typeof AuthenticatedInvoicesImportRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedPurchaseOrdersImportRoute: typeof AuthenticatedPurchaseOrdersImportRoute
  AuthenticatedPurchaseOrdersImportHistoryRoute: typeof AuthenticatedPurchaseOrdersImportHistoryRoute
  AuthenticatedPurchaseOrdersNewRoute: typeof AuthenticatedPurchaseOrdersNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedPurchaseOrdersIndexRoute: typeof AuthenticatedPurchaseOrdersIndexRoute
  AuthenticatedInvoicesIdEditRoute: typeof AuthenticatedInvoicesIdEditRoute
  AuthenticatedPurchaseOrdersIdEditRoute: typeof AuthenticatedPurchaseOrdersIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvoicesImportRoute: AuthenticatedInvoicesImportRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedPurchaseOrdersImportRoute:
    AuthenticatedPurchaseOrdersImportRoute,
  AuthenticatedPurchaseOrdersImportHistoryRoute:
    AuthenticatedPurchaseOrdersImportHistoryRoute,
  AuthenticatedPurchaseOrdersNewRoute: AuthenticatedPurchaseOrdersNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedPurchaseOrdersIndexRoute: AuthenticatedPurchaseOrdersIndexRoute,
  AuthenticatedInvoicesIdEditRoute: AuthenticatedInvoicesIdEditRoute,
  AuthenticatedPurchaseOrdersIdEditRoute:
    AuthenticatedPurchaseOrdersIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiExtractPoPdfRoute: ApiExtractPoPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
